services:
    backend:
        build:
            context: ./backend
            args:
                - GUNICORN_PORT=${GUNICORN_PORT}
                - PROMETHEUS_PORT=${PROMETHEUS_PORT}
        ports:
            - "${GUNICORN_PORT}:${GUNICORN_PORT}"
            - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
        environment:
            - GUNICORN_PORT=${GUNICORN_PORT}
            - PROMETHEUS_PORT=${PROMETHEUS_PORT}
        healthcheck:
            test: ["CMD-SHELL", "wget --spider http://0.0.0.0:${GUNICORN_PORT}/ || exit 1"]
            interval: 60s
            timeout: 10s
            retries: 2
            start_period: 30s
        networks:
            - backend_net
  
    backend_nginx:
        build:
            context: ./
            dockerfile: ./nginxb/Dockerfile
        volumes:
            - ./nginxb/conf.d:/etc/nginx/conf.d
            - ./ssl:/etc/ssl
        environment:
            - GUNICORN_PORT=${GUNICORN_PORT}
            - PROMETHEUS_PORT=${PROMETHEUS_PORT}
            - BACKEND_PORT=${BACK_PORT}
            - SERVER_NAME=${SERVER_NAME}
        networks:
            - public_net
            - backend_net
        ports:
            - "${BACK_PORT}:443"
        depends_on:
            - backend

    frontend:
        build: 
            context: ./frontend
            dockerfile: ./Dockerfile
        volumes:
            - ./frontend/nginx/conf.d:/etc/nginx/conf.d
            - ./ssl:/etc/ssl
        ports:
            - "${FRONT_PORT_HTTP}:80"
            - "${FRONT_PORT}:443"
        environment:
            - FRONT_PORT=${FRONT_PORT}
            - VITE_BACK_PORT=${VITE_BACK_PORT}
            - VITE_BACK_IP=${VITE_BACK_IP}
            - FRONT_NGINX_SERVER_NAME=${FRONT_NGINX_SERVER_NAME}
        healthcheck:
            test: ["CMD-SHELL", "curl --fail https://localhost:443 || exit 1"]
            interval: 60s
            timeout: 5s
            retries: 2
            start_period: 15s
        depends_on:
            - backend
        networks:
            - public_net

networks:
    public_net:
    backend_net:
        # internal: true
        driver: bridge
