name: Backend Tests

on:
    push:
        paths:
            - 'backend/'
    pull_request:
        paths:
            - 'backend/'

jobs:
  tests:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.3
        

      - name: Install dependencies
        run: |
          cd ./backend
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --tb=short --disable-warnings -q