name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GUNICORN_PORT: 8081
      FRONT_PORT: 3001
      PROMETHEUS_PORT: 9901
      VITE_BACK_PORT: 1213

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        docker compose version

    - name: Start services
      run: |
        docker compose up -d
        sleep 3

    - name: Test backend (index page) | gunicorn
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:${{ env.GUNICORN_PORT }}/)
        if [ "$response" -ne 200 ]; then
          echo "Backend test failed: Response code $response"
          exit 1
        else
          echo "Backend test passed: Response code 200"
        fi

    - name: Test backend (get random word api) | gunicorn
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:${{ env.GUNICORN_PORT }}/get_random_word)
        if [ "$response" -ne 200 ]; then
          echo "Backend test failed: Response code $response"
          exit 1
        else
          echo "Backend test passed: Response code 200"
        fi
